CREATE TABLE MEMBER(
	MID VARCHAR(30) PRIMARY KEY,
	PASSWORD VARCHAR(30) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	ROLE VARCHAR(30) DEFAULT 'USER',
	IMAGEPATH VARCHAR(100) DEFAULT 'default.jpg'
);

INSERT INTO MEMBER VALUES('admin','1234','관리자','ADMIN','admin.jpg');
INSERT INTO MEMBER (MID,PASSWORD,NAME) VALUES('test','1234','테스트');

SELECT * FROM MEMBER;
DELETE FROM MEMBER WHERE MID='teemo';

DROP TABLE MEMBER;