CREATE TABLE CHECKID (
    IDCHECK VARCHAR(255) PRIMARY KEY
);

DROP TABLE CHECKID;

-- 예시 데이터 삽입
INSERT INTO CHECKID (IDCHECK) VALUES ('TEEMO');
INSERT INTO CHECKID (IDCHECK) VALUES ('YENA');

SELECT * FROM CHECKID;