CREATE TABLE MEMBER(
	MID VARCHAR(20) PRIMARY KEY,
	PASSWORD VARCHAR(20) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	ROLE VARCHAR(10) DEFAULT 'USER'
);

INSERT INTO MEMBER (MID,PASSWORD,NAME,ROLE) VALUES('admin','1234','관리자','ADMIN'); 
INSERT INTO MEMBER (MID,PASSWORD,NAME,ROLE) VALUES('teemo','1234','작은티모','USER'); 

SELECT * FROM MEMBER;

DROP TABLE MEMBER;