CREATE TABLE PRODUCT(
	NUM INT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	DETAILS VARCHAR(100),
	PRICE INT,
	CNT INT,
	SELLER VARCHAR(20) -- FK,외래키,외부키 == 상대 테이블의 PK를 받아옴
);

-- FK 제약조건(강제성) 추가
ALTER TABLE PRODUCT
ADD CONSTRAINT FK_SELLER
FOREIGN KEY (SELLER)
REFERENCES MEMBER(MID)
ON DELETE SET NULL; -- CASCADE

INSERT INTO PRODUCT VALUES((SELECT NVL(MAX(NUM),0)+1 FROM PRODUCT),'사이다','톡쏘는 칠성사이다',1200,5,'admin');
INSERT INTO PRODUCT VALUES((SELECT NVL(MAX(NUM),0)+1 FROM PRODUCT),'콜라','톡쏘는 코카콜라',1300,2,'admin');
INSERT INTO PRODUCT VALUES((SELECT NVL(MAX(NUM),0)+1 FROM PRODUCT),'망고 스무디','달달한 망고 스무디',3800,0,'admin');

DROP TABLE PRODUCT;

SELECT
	P.NUM,
	P.NAME AS P_NAME,
	P.DETAILS,
	P.PRICE,
	P.CNT,
	M.NAME AS M_NAME
FROM
	PRODUCT P
JOIN
	MEMBER M
ON
	P.SELLER=M.MID;

INSERT INTO PRODUCT VALUES(4,'아샷추','아이스티에 샷 추가',3000,11,'teemo');
DELETE FROM MEMBER WHERE MID='teemo';

SELECT * FROM PRODUCT;

SELECT
	P.NUM,
	P.NAME AS P_NAME,
	P.DETAILS,
	P.PRICE,
	P.CNT,
	NVL(M.NAME,'탈퇴한 판매자입니다.') AS M_NAME
FROM
	PRODUCT P
LEFT JOIN
	MEMBER M
ON
	P.SELLER=M.MID;