CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR(100) PRIMARY KEY,
	MEMBER_NAME VARCHAR(50) NOT NULL,
	MEMBER_PASSWORD VARCHAR(100) NOT NULL,
	MEMBER_PHONE VARCHAR(50) NOT NULL,
	MEMBER_REGISTRATION_DATE DATE DEFAULT SYSDATE,
	MEMBER_PROFILE VARCHAR(2048) DEFAULT 'default.jpg',
	MEMBER_CURRENT_POINT INT DEFAULT 0,
	MEMBER_TOTAL_POINT INT DEFAULT 0,
	MEMBER_CREW_NUM INT DEFAULT NULL,
	MEMBER_CREW_JOIN_DATE DATE DEFAULT NULL,
	MEMBER_LOCATION VARCHAR(100) NOT NULL,
	MEMBER_ROLE CHAR(1) DEFAULT 'F' CHECK (MEMBER_ROLE IN ('T', 'F'))
);
--외래키 제약조건 추가
ALTER TABLE MEMBER
ADD CONSTRAINT FK_CREW_NUM
FOREIGN KEY (MEMBER_CREW_NUM)
REFERENCES CREW(CREW_NUM)
ON DELETE SET NULL;

-- 관리자 권한 추가
ALTER TABLE MEMBER
ADD MEMBER_ROLE CHAR(1) DEFAULT 'F' CHECK (MEMBER_ROLE IN ('T', 'F'));

ALTER TABLE MEMBER
MODIFY MEMBER_PROFILE DEFAULT 'default.jpg';

select * from MEMBER;

SELECT MEMBER_ID,MEMBER_PASSWORD,MEMBER_NAME,MEMBER_PHONE,MEMBER_PROFILE,MEMBER_REGISTRATION_DATE,MEMBER_CURRENT_POINT,MEMBER_TOTAL_POINT,MEMBER_CREW_NUM,MEMBER_CREW_JOIN_DATE,MEMBER_LOCATION,MEMBER_ROLE
			FROM MEMBER
			WHERE MEMBER_ID = 'user@naver.com' AND MEMBER_PASSWORD='1234'

			delete from member where MEMBER_ID = 'user@naver.com';
			
--샘플데이터 작성
INSERT INTO MEMBER(MEMBER_ID,MEMBER_NAME,MEMBER_PASSWORD,MEMBER_PHONE,MEMBER_LOCATION,MEMBER_ROLE) 
VALUES('user@naver.com','샘플이름1','1234','1234','샘플지역1','T');
INSERT INTO MEMBER(MEMBER_ID,MEMBER_NAME,MEMBER_PASSWORD,MEMBER_PHONE,MEMBER_LOCATION) 
VALUES('user2@naver.com','샘플이름2','샘플비밀번호2','1234','샘플지역2');
INSERT INTO MEMBER(MEMBER_ID,MEMBER_NAME,MEMBER_PASSWORD,MEMBER_PHONE,MEMBER_LOCATION) 
VALUES('user3@naver.com','샘플이름3','샘플비밀번호3','1234','샘플지역3');
INSERT INTO MEMBER(MEMBER_ID,MEMBER_NAME,MEMBER_PASSWORD,MEMBER_PHONE,MEMBER_LOCATION) 
VALUES('user4@naver.com','샘플이름4','샘플비밀번호4','1324','샘플지역4');

INSERT INTO MEMBER(MEMBER_ID,MEMBER_NAME,MEMBER_PASSWORD,MEMBER_PHONE,MEMBER_LOCATION,MEMBER_ROLE) 
VALUES('yena092582@gmail.com','주예나','1234','01042780927','서울','T');
--ID 검색 (관리자 추가된거 확인)
SELECT MEMBER_ID,MEMBER_PASSWORD,MEMBER_NAME,MEMBER_PHONE,MEMBER_PROFILE,MEMBER_REGISTRATION_DATE,MEMBER_CURRENT_POINT,MEMBER_TOTAL_POINT,MEMBER_CREW_NUM,MEMBER_CREW_JOIN_DATE,MEMBER_LOCATION,MEMBER_ROLE
FROM MEMBER
WHERE ID = '샘플유저1';

--ID, PASSWORD 검색
SELECT MEMBER_ID,MEMBER_PASSWORD,MEMBER_NAME,MEMBER_PHONE,MEMBER_PROFILE,MEMBER_REGISTRATION_DATE,MEMBER_CURRENT_POINT,MEMBER_TOTAL_POINT,MEMBER_CREW_NUM,MEMBER_CREW_JOIN_DATE,MEMBER_LOCATION,MEMBER_ROLE
FROM MEMBER
WHERE ID = '샘플유저1' AND PASSWORD='샘플비밀번호1';

--크루에 가입되지않은 유저 검색
SELECT MEMBER_ID,MEMBER_PASSWORD,MEMBER_NAME,MEMBER_PHONE,MEMBER_PROFILE,MEMBER_REGISTRATION_DATE,MEMBER_CURRENT_POINT,MEMBER_TOTAL_POINT,MEMBER_CREW_NUM,MEMBER_CREW_JOIN_DATE,MEMBER_LOCATION,MEMBER_ROLE
FROM MEMBER
WHERE CREW_ID = NULL AND ROLE='F';

--누적포인트 랭킹
SELECT MEMBER_ID,MEMBER_PASSWORD,MEMBER_NAME,MEMBER_PHONE,MEMBER_PROFILE,MEMBER_REGISTRATION_DATE,MEMBER_CURRENT_POINT,MEMBER_TOTAL_POINT,MEMBER_CREW_NUM,MEMBER_CREW_JOIN_DATE,MEMBER_LOCATION,MEMBER_ROLE
FROM MEMBER
ORDER BY MEMBER_TOTAL_POINT DESC
WHERE MEMBER_ROLE='F';

--PK로 유저 DB에서 삭제
DELETE FROM MEMBER WHERE MEMBER_ID = '샘플유저1' AND MEMBER_ID <> 'admin';

DELETE FROM MEMBER WHERE MEMBER_ID ='yena092582@gmail.com';
UPDATE MEMBER
SET
	MEMBER_NAME = '샘플이름1',
	MEMBER_PROFILE = NULL,
	MEMBER_PHONENUMBER = '샘플번호11',
	MEMBER_LOCATION = '샘플지역11',
	--MEMBER_CREW_NUM = 1
	--MEMBER_CREW_JOIN_DATE = SYSDATE
WHERE MEMBER_ID = '샘플유저2'

--크루가입
UPDATE MEMBER
SET
	MEMBER_CREW_NUM = ?,
	MEMBER_CREW_JOIN_DATE = SYSDATE
WHERE ID = ?

--크루 리더인지 확인
SELECT 
	M.MEMBER_NAME
FROM
	MEMBER M
JOIN
	CREW C
ON
	C.CREW_LEADER = M.MEMBER_ID
WHERE
	C.CREW_NUM = ?

--관리자 권한 변경
UPDATE MEMBER SET MEMBER_ROLE = 'T' WHERE MEMBER_ID = '샘플유저2';

--신규회원 목록 출력(7일)
SELECT MEMBER_ID,MEMBER_PASSWORD,MEMBER_NAME,MEMBER_PHONE,MEMBER_PROFILE,MEMBER_REGISTRATION_DATE,MEMBER_CURRENT_POINT,MEMBER_TOTAL_POINT,MEMBER_CREW_NUM,MEMBER_CREW_JOIN_DATE,MEMBER_LOCATION,MEMBER_ROLE
FROM member
WHERE MEMBER_REGISTRATION_DATE >= SYSDATE - INTERVAL '7' DAY AND ROLE='F';

SELECT * FROM MEMBER;


DROP TABLE MEMBER;