CREATE TABLE REPLY(
	RID INT PRIMARY KEY,
	BID INT NOT NULL,
	CONTENT VARCHAR(30) NOT NULL,
	WRITER VARCHAR(30) NOT NULL
);

ALTER TABLE REPLY
ADD CONSTRAINT FK_BID
FOREIGN KEY (BID)
REFERENCES BOARD(BID)
ON DELETE CASCADE;
ALTER TABLE REPLY
ADD CONSTRAINT FK_REPLY_WRITER
FOREIGN KEY (WRITER)
REFERENCES MEMBER(MID)
ON DELETE CASCADE;

INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),1000)+1 FROM REPLY),101,'관리자가 작성한 댓글','admin');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),1000)+1 FROM REPLY),101,'사용자가 작성한 댓글','test');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),1000)+1 FROM REPLY),102,'관리자가 작성한 댓글','admin');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),1000)+1 FROM REPLY),102,'사용자가 작성한 댓글','test');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),1000)+1 FROM REPLY),103,'관리자가 작성한 댓글','admin');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),1000)+1 FROM REPLY),103,'사용자가 작성한 댓글','test');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),1000)+1 FROM REPLY),104,'관리자가 작성한 댓글','admin');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),1000)+1 FROM REPLY),104,'사용자가 작성한 댓글','test');

SELECT * FROM REPLY;
SELECT R.RID,R.BID,B.TITLE,R.CONTENT,M.NAME FROM REPLY R JOIN BOARD B ON R.BID=B.BID JOIN MEMBER M ON R.WRITER=M.MID;
SELECT R.RID,R.BID,R.CONTENT,M.NAME FROM REPLY R JOIN BOARD B ON R.BID=B.BID JOIN MEMBER M ON R.WRITER=M.MID WHERE R.BID=101;

DROP TABLE REPLY;